eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampler:
      probability: 1.0
server:
  port: 9091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
  main:
    web-application-type: reactive
